version: '3.1'

services:

  db:
    container_name: db   
    image: mysql:8.0.27
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    ports:
      - "3300:3306"    
    environment:
      DB_HOST: localhost
      MYSQL_ROOT_PASSWORD: mipassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: userwp
      MYSQL_PASSWORD: mipassword
    networks:
      - wp-multi

  wordpress:
    container_name: wp-public
    image: wordpress:latest       
    depends_on:
      - db
    volumes:
      - ./wordpress:/var/www/html  
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/php.ini   
    restart: unless-stopped
    ports:
      - "8000:80" 
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: userwp
      WORDPRESS_DB_PASSWORD: mipassword
      WORDPRESS_TABLE_PREFIX: 'wpdb_' 
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_ALLOW_MULTISITE', true);
        define('WP_POST_REVISIONS', 5);
        define('MEDIA_TRASH', true);
        define('WP_MEMORY_LIMIT', '512M');
        
    networks:
      - wp-multi

  phpmyadmin:
    container_name: phpMyAdmin
    image: phpmyadmin/phpmyadmin    
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: mipassword
    networks:
      - wp-multi

networks:
  wp-multi:

volumes:
  db_data: 
  wordpress:
